/*------------------------------------------------------------------------+
 * +xxxxxxxxxxxxxxxxxxxxxx SKYSOFT PORTUGAL SA xxxxxxxxxxxxxxxxxxxxxxxxx+ *
 * |                                                                    | *
 * | LEGAL NOTICE: The source code contained herein is not intended to  | *
 * | allow the development of source code or software for use or        | *
 * | distribution. This file contains SKYSOFT PORTUGAL, SA proprietary  | *
 * | information and is supplied on the condition that it shall solely  | *
 * | be used within the terms of the AVT License Agreement. Except as   | *
 * | otherwise provided thereof, you may not,without prior written      | *
 * | permission from SKYSOFT PORTUGAL, S.A. provide, or otherwise       | *
 * | disclose information regarding any discovered bugs, errors,        | *
 * | architecture issues or problems with the Source Code or Compiled   | *
 * | Code to any other party.                                           | *
 * |                                                                    | *
 * +--------------------------------------------------------------------+ *
 *                                                                        *
 * +xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+ *
 * |                                                                    | *
 * | FILE: AVT_SamplingPorts.h                                          | *
 * | VERSION: A653-1 R1.0                                               | *
 * | $Log$                                                              | *
 * |                                                                    | *
 * | CSCI NAME: SAMPLINGPORTS                                           | *
 * | UNIT NAME: AVT                                                     | *
 * |                                                                    | *
 * | DESCRIPTION: Header file with functions prototypes, definitions    | *
 * |              concern to SamplingPorts.c source.                    | *
 * |                                                                    | *
 * |                                                                    | *
 * | AUTHOR:                                                            | *
 * | DATE:   29/08/2002                                                 | *
 * |                                                                    | *
 * |                                                                    | *
 * +--------------------------------------------------------------------+ *
 *------------------------------------------------------------------------*/
#ifndef AVT__SAMPLING_PORTS_H_
#define AVT__SAMPLING_PORTS_H_

#include "AVT_TestTool.h"


/* Struct to store the errors generated by */
/* "CheckCtrateSamplingPort" function */
typedef struct
{
  unsigned ReturnCode     : 1;
  unsigned GetStatus      : 1;
  unsigned MaxMessageSize : 1;
  unsigned PortDirection  : 1;
  unsigned RefreshPeriod  : 1;
} CREATE_SAMPLING_PORT_ERROR;


/* Struct to store the errors generated by */
/* "CheckWriteSamplingMessage" and */
// "CheckGetSamplingPortId" function */
typedef struct
{
  unsigned ReturnCode : 1;
  unsigned GetStatus  : 1;
} WRITE_SAMPLING_MESSAGE_ERROR,
  GET_SAMPLING_PORT_ID_ERROR;


/* Struct to store the errors generated by */
/* "CheckReadSamplingPort" function */
typedef struct
{
  unsigned ReturnCode   : 1;
  unsigned MessageSize  : 1;
  unsigned Message      : 1;
  unsigned GetStatus    : 1;
} READ_SAMPLING_MESSAGE_ERROR;


/* Struct to store the errors generated by */
/* "CheckGetSamplingPortStatus" function */
typedef struct
{
  unsigned ReturnCode    : 1;
} GET_SAMPLING_PORT_STATUS_ERROR;


/********************************/
/* functions module prototypes  */
/********************************/
CREATE_SAMPLING_PORT_ERROR
CheckCreateSamplingPort( SAMPLING_PORT_NAME_TYPE    InPortName,
                         MESSAGE_SIZE_TYPE          InMaxMessageSize,
                         PORT_DIRECTION_TYPE        InPortDirection,
                         SYSTEM_TIME_TYPE           InRefreshPeriod,
                         RETURN_CODE_TYPE           InReturnCode,
                         SAMPLING_PORT_ID_TYPE     *OutPortId,
                         SAMPLING_PORT_STATUS_TYPE *OutStatus,
                         RETURN_CODE_TYPE          *OutReturnCode );

WRITE_SAMPLING_MESSAGE_ERROR
CheckWriteSamplingMessage( SAMPLING_PORT_ID_TYPE      InPortId,
                           APEX_BYTE                 *InMessage,
                           MESSAGE_SIZE_TYPE          InSize,
                           RETURN_CODE_TYPE           InReturnCode,
                           SAMPLING_PORT_STATUS_TYPE *OutStatus,
                           RETURN_CODE_TYPE          *OutReturnCode );

GET_SAMPLING_PORT_ID_ERROR
CheckGetSamplingPortId(  SAMPLING_PORT_NAME_TYPE    InPortName,
                         RETURN_CODE_TYPE           InReturnCode,
                         SAMPLING_PORT_ID_TYPE     *OutPortId,
                         SAMPLING_PORT_STATUS_TYPE *OutStatus,
                         RETURN_CODE_TYPE          *OutReturnCode );

READ_SAMPLING_MESSAGE_ERROR
CheckReadSamplingMessage( SAMPLING_PORT_ID_TYPE      InPortId,
                          RETURN_CODE_TYPE           InReturnCode,
                          APEX_BYTE                 *InMessage,
                          MESSAGE_SIZE_TYPE          InMsgSize,
                          APEX_BYTE                 *OutMessage,
                          MESSAGE_SIZE_TYPE         *OutMsgSize,
                          VALIDITY_TYPE             *OutPortValidity,
                          SAMPLING_PORT_STATUS_TYPE *OutStatus,
                          RETURN_CODE_TYPE          *OutReturnCode,
			              int                       LogFlag );

GET_SAMPLING_PORT_STATUS_ERROR
CheckGetSamplingPortStatus( SAMPLING_PORT_ID_TYPE      InPortId,
                            RETURN_CODE_TYPE           InReturnCode,
                            SAMPLING_PORT_STATUS_TYPE *OutStatus,
                            RETURN_CODE_TYPE          *OutReturnCode );


#endif
/* +xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+ *
 * |                                                                    | *
 * |                   END OF FILE: AVT_SamplingPorts.h                 | *
 * |                                                                    | *
 * +xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+ */
