#!/bin/bash
echo "Starting post-commit hook..."

MESSAGE=$(git log -1 HEAD --pretty=format:%s)

CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)

# Loop through the list of changed files and apply MISRAivoso.py to each one
for FILE in $CHANGED_FILES; do
  python3 utils/misraivoso/MISRAivoso.py --correction --src air/ --src-file "$FILE"
done

git add .
git commit -m "$MESSAGE (MISRA)"

echo "Terminating post-commit hook..."