#!/bin/bash
echo "Starting post-commit hook..."

MESSAGE=$(git log -1 HEAD --pretty=format:%s)

# Push current commit to remote repository
git push

if [[ $? -eq 0 ]]; then
  echo "Push was successful."
  
  python3 utils/misraivoso/MISRAivoso.py --correction --src air/ --src-file-list air/pmk # [--include-comments] [--delete-comments]
  python3 utils/misraivoso/MISRAivoso.py --correction --src air/ --src-file-list air/libs
  python3 utils/misraivoso/MISRAivoso.py --correction --src air/ --src-file-list air/pos/bare
  python3 utils/misraivoso/MISRAivoso.py --correction --src air/ --src-file-list air/tools
  git add .
  git commit -m "$MESSAGE (MISRA)"
  git push

else
  echo "Push failed, please check your connection."
  git reset --soft HEAD~1

fi

echo "Terminating post-commit hook..."