.build-executable: &build-executable
    - $AIR/configure
    - make clean
    - make
    - if ! test -f ./executable/AIRAPP.exe; then echo "Executable doens\'t exist." && exit 1; fi

.check-and-publish: &check-and-publish
    - $AIR/../utils/gitlab-runner/testcheck.py
    - $UTILS/publish_example.bash

00001_arm_zynqz1:
    stage: examples
    tags: 
        - ARM
    script:
        - cd $AIR/examples/private-example/private/arm_unit_tests/lionel
        - *build-executable
        - $UTILS/runQemu.bash executable/AIRAPP.exe
        - *check-and-publish

hello_world_arm_zynqz1:
    stage: examples
    tags: 
        - ARM
    script:
        - cd $AIR/examples/hello_world
        - *build-executable
        - $UTILS/runQemu.bash executable/AIRAPP.exe
        - *check-and-publish

# ARM-TEST-DEF-00009:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00009
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00010:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00010
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00012:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00012
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00021:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00021
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00022:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00022
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00023:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00023
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00500:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00500
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00510:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00510
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00540:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00540
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00560:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00560
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-00600:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-00600
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01390:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01390
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01570:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01570
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01590:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01590
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01610:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01610
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01650:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01650
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01730:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01730
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01740:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01740
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01741:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01741
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-01750:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01750
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-02100:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-01750
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-80000:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-80000
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-80010:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-80010
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-80060:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-80060
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-80080:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-80080
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-80300:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-80300
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-80400:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-80400
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-80401:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-80401
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish

# ARM-TEST-DEF-80420:
#     stage: validation_tests
#     tags: 
#         - ARM
#     script:
#         - cd $AIR/examples/private-example/private/validation/TEST-DEF-80420
#         - *build-executable
#         - $UTILS/runQemu.bash executable/AIRAPP.exe
#         - *check-and-publish
