/*------------------------------------------------------------------------+
 * +xxxxxxxxxxxxxxxxxxxxxx SKYSOFT PORTUGAL SA xxxxxxxxxxxxxxxxxxxxxxxxx+ *
 * |                                                                    | *
 * | LEGAL NOTICE: The source code contained herein is not intended to  | *
 * | allow the development of source code or software for use or        | *
 * | distribution. This file contains SKYSOFT PORTUGAL, SA proprietary  | *
 * | information and is supplied on the condition that it shall solely  | *
 * | be used within the terms of the AVT License Agreement. Except as   | *
 * | otherwise provided thereof, you may not,without prior written      | *
 * | permission from SKYSOFT PORTUGAL, S.A. provide, or otherwise       | *
 * | disclose information regarding any discovered bugs, errors,        | *
 * | architecture issues or problems with the Source Code or Compiled   | *
 * | Code to any other party.                                           | *
 * |                                                                    | *
 * +--------------------------------------------------------------------+ *
 *                                                                        *
 * +xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+ *
 * |                                                                    | *
 * | FILE: AVT_Partition.h                                              | *
 * | VERSION: A653-1 R1.0                                               | *
 * | $Log$                                                              | *
 * |                                                                    | *
 * | CSCI NAME: AVT_PARTITION                                           | *
 * | UNIT NAME: AVT                                                     | *
 * |                                                                    | *
 * | DESCRIPTION: Header file with functions prototypes, definitions    | *
 * |              concern to Partition.c source.                        | *
 * |                                                                    | *
 * |                                                                    | *
 * | AUTHOR:                                                            | *
 * | DATE:   28/08/2002                                                 | *
 * |                                                                    | *
 * |                                                                    | *
 * +--------------------------------------------------------------------+ *
 *------------------------------------------------------------------------*/
#ifndef _AVT_PARTITION_H_
#define _AVT_PARTITION_H_

#include "AVT_TestTool.h"

/* Struct to store the errors generated by */
/* "CheckGetPartitionStatus" function  */
typedef struct
{
  unsigned ReturnCode    : 1;
  unsigned Period        : 1;
  unsigned Duration      : 1;
  unsigned LockLevel     : 1;
  unsigned OperatingMode : 1;
} GET_PARTITION_STATUS_ERROR;

/* Struct to store the errors generated by */
/* "CheckSetPartitionMode" and "CheckGetPartitionStartCondition" */
/*  function  */
typedef struct
{
  unsigned ReturnCode : 1;
  unsigned GetStatus  : 1;
} SET_PARTITION_MODE_ERROR,
  GET_PARTITION_START_CONDITION_ERROR;



/********************************/
/* functions module prototypes  */
/********************************/

GET_PARTITION_STATUS_ERROR
CheckGetPartitionStatus( PARTITION_STATUS_TYPE *InStatus,
                         RETURN_CODE_TYPE       InReturnCode,
                         PARTITION_STATUS_TYPE *OutStatus,
                         RETURN_CODE_TYPE      *OutReturnCode );

SET_PARTITION_MODE_ERROR
CheckSetPartitionMode( OPERATING_MODE_TYPE    InOperMode,
                       RETURN_CODE_TYPE       InReturnCode,
                       PARTITION_STATUS_TYPE *OutStatus,
                       RETURN_CODE_TYPE      *OutReturnCode);

GET_PARTITION_START_CONDITION_ERROR
CheckGetPartitionStartCondition( RETURN_CODE_TYPE       InReturnCode,
                                 START_CONDITION_TYPE  *OutType,
                                 PARTITION_STATUS_TYPE *OutStatus,
                                 RETURN_CODE_TYPE      *OutReturnCode );

#endif
/* +xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+ *
 * |                                                                    | *
 * |                   END OF FILE: AVT_Partition.h                     | *
 * |                                                                    | *
 * +xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+ */
