/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Partition Initialization
 * ============================================================================
 */

#include <bare.h>

/**
 * @brief Partition entry point
 */
extern int entry_func() __attribute__ ((weak));

/**
 * @brief Program entry point
 */
int main(void) {

    /* call entry point */
    if (entry_func != NULL) {
        entry_func();
    }

    return 0;
}
