/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Shared Memory configuration
 * ============================================================================
 */

#include <usr_config.h>

#include <partition.h>
#include <sharedmemory.h>

/**
 * @brief Partition table (defined in usr_partitions.c)
 */
extern pmk_partition_t usr_partition_table[USR_PARTITIONS];


/**
 * @brief Shared Memory Configuration Table
 */
pmk_shm_t usr_shared_memory_table[USR_SHARED_MEMORY] = \
{
};
