/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Channels configuration
 * ============================================================================
 */

#include <ports.h>
#include <ports_queuing.h>
#include <ports_sampling.h>
#include <usr_config.h>

/**
 * @brief Ports
 */
static pmk_port_t usr_ports[] = \
{
    {   /* Sampling Port (Name: SEND_SAMP1) */
        .id         = 0,
        .name       = "SEND_SAMP1",
        .direction  = XKY_SOURCE_PORT,
    }, 
    {   /* Sampling Port (Name: RECV_SAMP1) */
        .id         = 1,
        .name       = "RECV_SAMP1",
        .direction  = XKY_DESTINATION_PORT,
    }, 
    {   /* Sampling Port (Name: SEND_SAMP2) */
        .id         = 0,
        .name       = "SEND_SAMP2",
        .direction  = XKY_SOURCE_PORT,
    }, 
    {   /* Sampling Port (Name: RECV_SAMP2) */
        .id         = 1,
        .name       = "RECV_SAMP2",
        .direction  = XKY_DESTINATION_PORT,
    }, 
};

/**
 * @brief Channel 0 configuration
 */
static pmk_sampling_config_t usr_channel0_configuration = \
{
    .max_message_size   = 32,
    .refresh_period     = 1000,
};

/**
 * @brief Channel 1 configuration
 */
static pmk_sampling_config_t usr_channel1_configuration = \
{
    .max_message_size   = 32,
    .refresh_period     = 1000,
};

/**
 * @brief Partition 0 Port Table
 */
pmk_port_t *usr_partition0_ports[2] = \
{
    &usr_ports[0],
    &usr_ports[1],
};

/**
 * @brief Partition 1 Port Table
 */
pmk_port_t *usr_partition1_ports[2] = \
{
    &usr_ports[2],
    &usr_ports[3],
};

/**
 * @brief Channel 0 source ports
 */
pmk_port_t *usr_channel0_source_ports[1] = \
{
    &usr_ports[0],
};

/**
 * @brief Channel 0 destination ports
 */
pmk_port_t *usr_channel0_destination_ports[1] = \
{
    &usr_ports[3],
};

/**
 * @brief Channel 1 source ports
 */
pmk_port_t *usr_channel1_source_ports[1] = \
{
    &usr_ports[2],
};

/**
 * @brief Channel 1 destination ports
 */
pmk_port_t *usr_channel1_destination_ports[1] = \
{
    &usr_ports[1],
};

/**
 * @brief Module Communication Channels table
 */
pmk_channel_t usr_channels_table[USR_CHANNELS] = \
{
    {   /* Channel (Id: 1, Name: SAMPLING1) */
        .id             = 1,
        .name           = "SAMPLING1",
        .type           = XKY_SAMPLING_PORT,
        .src            = \
        {
            .length     =  1,
            .elements   = (void *)usr_channel0_source_ports
        },
        .dst            = \
        {
            .length     =  1,
            .elements   = (void *)usr_channel0_destination_ports
        },
        .configuration  = (void *)&usr_channel0_configuration,
    },
    {   /* Channel (Id: 1, Name: SAMPLING2) */
        .id             = 1,
        .name           = "SAMPLING2",
        .type           = XKY_SAMPLING_PORT,
        .src            = \
        {
            .length     =  1,
            .elements   = (void *)usr_channel1_source_ports
        },
        .dst            = \
        {
            .length     =  1,
            .elements   = (void *)usr_channel1_destination_ports
        },
        .configuration  = (void *)&usr_channel1_configuration,
    }
};
