/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : General XKY application configuration
 * ============================================================================
 */

#define USR_US_PER_TICK                                         (1000)
#define USR_PARTITIONS                                          (2)
#define USR_SCHEDULES                                           (1)
#define USR_CHANNELS                                            (2)
#define USR_CORES                                               (2)
#define USR_SHARED_MEMORY                                       (0)
