/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : SPARC specific configuration
 * ============================================================================
 */

#include <cpu.h>

/**
 * @brief SPARC specific configuration
 */
arch_configuration_t arch_configuration = { \
    .mmu_context_entries   = 2,
    .mmu_l1_tables_entries = 2,
    .mmu_l2_tables_entries = 40,
    .mmu_l3_tables_entries = 0,
};
