dnl $Id: bsp-configure.m4 7135 2010-04-09 09:58:30Z mcoutinho $

dnl RTEMS_BSP_CONFIGURE
dnl Common macro to be included by all bsp-configure.acs
AC_DEFUN([RTEMS_BSP_CONFIGURE],
[
  AC_PREREQ(2.60)
  AM_MAINTAINER_MODE
  RTEMS_ENV_RTEMSBSP

  RTEMS_CHECK_CUSTOM_BSP(RTEMS_BSP)

  AC_CONFIG_HEADERS([include/bspopts.h])

  RTEMS_PROJECT_ROOT

  RTEMS_CHECK_MULTIPROCESSING
])
