/* 
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an 
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Partition Initialization
 * ============================================================================
 */

#include <bsp.h>

#include <air.h>
#include <pmk_plugin.h>

#include <imaspex.h>

extern int test_printf();

/* Kernel Threads / Main Init launcher */
rtems_task Init (rtems_task_argument ignored) {

	rtems_status_code 	rc;
	
	/* imaspex start */
    //imaspex_init();
	
	/* partition user code entry 
	 * (defined in the module's xml config file) */
	 if (test_printf != NULL) {
	    test_printf();
	}
	

	rc = rtems_task_suspend		( RTEMS_SELF );
	rc = rtems_task_delete      ( RTEMS_SELF );
	rc = rtems_task_is_suspended( RTEMS_SELF );
	rc = rtems_task_resume		( RTEMS_SELF );
	
}
/* configuration information */

#define CONFIGURE_MAXIMUM_TASKS 			15

/** a semaphore is added per each port used in the partition */ 
#define CONFIGURE_MAXIMUM_SEMAPHORES		(4+0)

#include "../config/usr_rtems_config.h"

#include <rtems/confdefs.h>
