/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : General XKY application configuration
 * ============================================================================
 */

#define USR_US_PER_TICK                                         (10000)
#define USR_PARTITIONS                                          (4)
#define USR_SCHEDULES                                           (2)
#define USR_CHANNELS                                            (0)
#define USR_CORES                                               (1)
#define USR_SHARED_MEMORY                                       (0)
