/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Module Schedules configuration
 * ============================================================================
 */

#include <schedule.h>
#include <partition.h>
#include <usr_config.h>

/**
 * @brief Partition table (defined in usr_partitions.c)
 */
extern pmk_partition_t usr_partition_table[USR_PARTITIONS];

/**
 * @brief Schedule 0: scheduled partitions
 */
static pmk_partition_schedule_t usr_schedule0_partitions[3] = \
{
    {   /* Partition Schedule (Id: 10, Name: master) */
	    .partition    = &usr_partition_table[0],
	    .set_schedule = 1,
	    .action       = PMK_SCHED_CHANGE_ACTION_IGNORE,
	    .period       = 300ULL,
	    .duration     = 100ULL,
    },
    {   /* Partition Schedule (Id: 1, Name: p1) */
	    .partition    = &usr_partition_table[1],
	    .set_schedule = 0,
	    .action       = PMK_SCHED_CHANGE_ACTION_IGNORE,
	    .period       = 300ULL,
	    .duration     = 100ULL,
    },
    {   /* Partition Schedule (Id: 2, Name: p2) */
	    .partition    = &usr_partition_table[2],
	    .set_schedule = 0,
	    .action       = PMK_SCHED_CHANGE_ACTION_IGNORE,
	    .period       = 300ULL,
	    .duration     = 100ULL,
    }
};

/**
 * @brief Schedule 0, core 0: windows
 */
static pmk_window_t usr_schedule0_windows0[3] = \
{
    {   /* Window (Id: 110) */
        .duration     = 100,
        .period_start = 1,
        .partition    = &usr_partition_table[0],
        .virtual_core = 0,
    },
    {   /* Window (Id: 11) */
        .duration     = 100,
        .period_start = 1,
        .partition    = &usr_partition_table[1],
        .virtual_core = 0,
    },
    {   /* Window (Id: 12) */
        .duration     = 100,
        .period_start = 1,
        .partition    = &usr_partition_table[2],
        .virtual_core = 0,
    }
};

/**
 * @brief Schedule 0: cores schedules
 */
static pmk_core_schedule_t usr_schedule0_cores[USR_CORES] = \
{
    { .count = 3, .windows = (void *)usr_schedule0_windows0 }
};
/**
 * @brief Schedule 1: scheduled partitions
 */
static pmk_partition_schedule_t usr_schedule1_partitions[3] = \
{
    {   /* Partition Schedule (Id: 10, Name: master) */
	    .partition    = &usr_partition_table[0],
	    .set_schedule = 1,
	    .action       = PMK_SCHED_CHANGE_ACTION_IGNORE,
	    .period       = 150ULL,
	    .duration     = 50ULL,
    },
    {   /* Partition Schedule (Id: 2, Name: p2) */
	    .partition    = &usr_partition_table[2],
	    .set_schedule = 0,
	    .action       = PMK_SCHED_CHANGE_ACTION_IGNORE,
	    .period       = 150ULL,
	    .duration     = 50ULL,
    },
    {   /* Partition Schedule (Id: 3, Name: p3) */
	    .partition    = &usr_partition_table[3],
	    .set_schedule = 0,
	    .action       = PMK_SCHED_CHANGE_ACTION_IGNORE,
	    .period       = 150ULL,
	    .duration     = 50ULL,
    }
};

/**
 * @brief Schedule 1, core 0: windows
 */
static pmk_window_t usr_schedule1_windows0[3] = \
{
    {   /* Window (Id: 210) */
        .duration     = 50,
        .period_start = 1,
        .partition    = &usr_partition_table[0],
        .virtual_core = 0,
    },
    {   /* Window (Id: 22) */
        .duration     = 50,
        .period_start = 1,
        .partition    = &usr_partition_table[2],
        .virtual_core = 0,
    },
    {   /* Window (Id: 23) */
        .duration     = 50,
        .period_start = 1,
        .partition    = &usr_partition_table[3],
        .virtual_core = 0,
    }
};

/**
 * @brief Schedule 1: cores schedules
 */
static pmk_core_schedule_t usr_schedule1_cores[USR_CORES] = \
{
    { .count = 3, .windows = (void *)usr_schedule1_windows0 }
};

/**
 * @brief Module Schedules Configuration
 */
pmk_schedule_t usr_schedule_table[USR_SCHEDULES] = \
{
    {   /* Schedule (Id: 1, Name: schedA) */
        .id         = 1,
        .name       = "schedA",
        .mtf        = 300,
        .initial    = 1,
        .partitions = { .length =  3, .elements = (void *)usr_schedule0_partitions },
        .cores      = usr_schedule0_cores,
    },
    {   /* Schedule (Id: 2, Name: schedB) */
        .id         = 2,
        .name       = "schedB",
        .mtf        = 150,
        .initial    = 0,
        .partitions = { .length =  3, .elements = (void *)usr_schedule1_partitions },
        .cores      = usr_schedule1_cores,
    },
};
