/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Channels configuration
 * ============================================================================
 */

#include <ports.h>
#include <ports_queuing.h>
#include <ports_sampling.h>
#include <usr_config.h>


/**
 * @brief Partition 0 Port Table
 */
pmk_port_t *usr_partition0_ports[0] = \
{
};

/**
 * @brief Partition 1 Port Table
 */
pmk_port_t *usr_partition1_ports[0] = \
{
};

/**
 * @brief Partition 2 Port Table
 */
pmk_port_t *usr_partition2_ports[0] = \
{
};

/**
 * @brief Partition 3 Port Table
 */
pmk_port_t *usr_partition3_ports[0] = \
{
};

/**
 * @brief Module Communication Channels table
 */
pmk_channel_t usr_channels_table[USR_CHANNELS] = \
{
};
