
LOG_REQUIRED_TAG_MISSING                  = "Required element {0} not found"
LOG_TOO_MANY_TAGS                         = "{0} elements of {1} were found, only {2} will be used"
LOG_ATTRIBUTE_MISSING                     = "Required attribute {0} not found in {1}"
LOG_ATTRIBUTE_INVALID_0                   = "Line {0}, value '{1}' for attribute '{2}' is not valid"
LOG_ATTRIBUTE_INVALID_1                   = "Line {0}, value '{1}' for attribute '{2}' is not valid, using default value '{3}'"
LOG_TEXT_INVALID_0                        = "Line {0}, value '{1}' for tag '{2}' is not valid"
LOG_TEXT_INVALID_1                        = "Line {0}, value '{1}' for tag '{2}' is not valid, using default value '{3}'"
LOG_PORT_REDEFINED                        = "Line {0}, Port (Name = {1}) is already defined in Partition (ID = {2}, Name = '{3}')"


LOG_EVENT_MODULE_CONFIG                   = "Parsing Module Configuration"
LOG_EVENT_SYSTEM_HM                       = "Parsing System Health-Monitor Configuration"
LOG_EVENT_MODULE_HM                       = "Parsing Module Health-Monitor Configuration"
LOG_EVENT_PARTITIONS                      = "Parsing Partitions Configuration"
LOG_EVENT_SCHEDULES                       = "Parsing Scheduling Configuration"
LOG_EVENT_PARTITIONS_HM                   = "Parsing Partitions Health-Monitor Configuration"
LOG_EVENT_CONNECTION_TABLE                = "Parsing Module Connection Table"
LOG_EVENT_SHARED_MEMORY                   = "Parsing Shared Memory Blocks"
LOG_EVENT_PARTITION_CONFIG                = "Generating {0} configuration files"
LOG_EVENT_APP_CONFIG                      = "Generating AIR application configuration files"

LOG_EVENT_IOP_LDEVICES                    = "Parsing Logical Devices"
LOG_EVENT_IOP_REMOTE_PORTS                = "Parsing Remote Ports"
LOG_EVENT_IOP_PDEVICES                    = "Parsing Physical Devices"
LOG_EVENT_IOP_SCHEDULE                    = "Parsing Schedules"

LOG_REDEFINITION                          = "Line {0}, redefinition of {1}"
LOG_UNDEFINED                             = "Line {0}, {1} is undefined"
LOG_UNDEFINED_SYSTEM_STATE_0              = "Line {0}, {1] is undefined in the System Health-Monitor Table"
LOG_UNDEFINED_SYSTEM_STATE_1              = "Line {0}, {1} is undefined for level {2}"
LOG_UNDEFINED_ERROR_LEVEL                 = "Line {0}, Error Id {1} is undefined for level {2}"
LOG_INVALID_TAG                           = "Line {0}, invalid tag '{1}'"

LOG_PARTITION_LIBRARY_INVALID             = "Line {0}, library {1} is not valid for {2}"
LOG_PARTITION_PERMISSION_INVALID          = "Line {0}, permission {1} is not valid for {2}"

LOG_SCHEDULE_INVALID_PERIOD               = "Line {0}, PeriodSeconds isn't a multiple of the {1} Major Time Frame"
LOG_SCHEDULE_INVALID_PERIOD_DURATION      = "{0} contains invalid period durations"
LOG_WINDOW_OVERFLOW_PERIOD                = "Line {0}, {1} overflows period of {2}"
LOG_WINDOW_OVERFLOW_1                     = "Line {0}, {1} overflows {2} (core {3})"
LOG_WINDOW_OVERFLOW_2                     = "Line {0}, {1} overflows {2} Major Time Frame (core {3})"
LOG_WINDOW_RESOLUTION                     = "Line {0}, {1} '{2}' exceeds the configured time resolution"
LOG_WINDOW_PERIOD_START_REDEFINITION      = "Line {0}, PartitionPeriodStart redefinition in {1}"
LOG_WINDOW_EXT_CORES_INVALID_0            = "Line {0}, invalid core usage for the Module configuration"
LOG_WINDOW_EXT_CORES_INVALID_1            = "Line {0}, invalid core usage for {1} configuration"
LOG_WINDOW_EXT_CORES_INVALID_2            = "{0} doesn't have a valid core usage for {1} configuration"

LOG_UNUSED_PORT                           = "Line {0}, {1} isn't used in any communication channel"
LOG_UNUSED_PARTITION                      = "Line {0}, {1} isn't used in any communication channel"
LOG_ALREADY_IN_USE_PORT                   = "Line {0}, {1} is already being used for another channel"
LOG_CHANNEL_ONLY_ONE_SRC                  = "Line {0}, {1} can only have one SOURCE port"
LOG_CHANNEL_ONLY_ONE_DST                  = "Line {0}, {1} can only have one DESTINATION port"
LOG_CHANNEL_MIX_PORTS                     = "Line {0}, {1} contains multiple types of ports"
LOG_CHANNEL_PORT_MISMATCH                 = "Line {0}, {1} port configuration mismatch"

LOG_UNSUPPORTED_DEVICE                    = "Line {0}, device {1} is not supported"
LOG_UNSUPPORTED_IOP                       = "Line {0}, IOP is not supported by the current target"

LOG_TARGET_NOT_SUPPORTED                  = "Target {0} is not supported by this configuration"
LOG_NOT_A653                              = "Value '{0}' for attribute '{1}' is not compliant with ARINC635"
