/** 
 * @file AVT_heritage.h
 * 
 *  COPYRIGHT (c) 2013
 *  GMV-SKYSOFT 
 *
 * @author Bruno Oliveira
 * @brief  AVT function prototypes for equivalent implementations and 
 *    missing ARINC functions workaround. AVT essential type definitions

 * 
 */


#ifndef _AVT_HERITAGE_H_
#define _AVT_HERITAGE_H_


#include <a653.h>
#include <rtems.h>

typedef enum 
{
	NOT_PERFORMED = 0,
	FAILED = 1,
	SUCESS = 2
} TEST_RESULT_TYPE;

typedef rtems_boolean BOOLEAN;


/* Struct to store the errors generated by 
 "CheckSetPartitionMode" and "CheckGetPartitionStartCondition" 
  function  */
typedef struct
{
  unsigned ReturnCode : 1;
  unsigned GetStatus  : 1;
} SET_PARTITION_MODE_ERROR,
  GET_PARTITION_START_CONDITION_ERROR;




/* Function Prototypes */


void print_testdef_result(TEST_RESULT_TYPE TestResult);

TEST_RESULT_TYPE EvaluateResult( BOOLEAN FlagOK );

void print_test_results(TEST_RESULT_TYPE TestResult);

void STOP_SELF( void );

void w_SET_PARTITION_MODE( 
	OPERATING_MODE_TYPE OperMode,
  RETURN_CODE_TYPE    *RetCode );


#endif
