/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Partition Initialization
 * ============================================================================
 */

#include <xky.h>
#include <rtems.h>
#include <imaspex.h>

/**
 * @brief Partition entry point
 */
extern int producer() __attribute__ ((weak));
/**
 * @brief Health-Monitor ISR handler
 */
static void hm_isr_handler(void) {

    /* get HM event */
    xky_hm_event_t hm_event;
    xky_syscall_get_hm_event(&hm_event);
}

/**
 * @brief Main RTEMS task
 */
rtems_task Init(rtems_task_argument ignored) {

    /* register HM ISR handler */
    rtems_isr_entry isr_ignored;
    rtems_interrupt_catch(
            (rtems_isr_entry)hm_isr_handler,
            XKY_IRQ_HM_EVENT,
            &isr_ignored);

    /* initialize IMASPEX */
    imaspex_init();

    /* call entry point */
    if (producer != NULL) {
        producer();
    }

    rtems_task_delete(RTEMS_SELF);
}

#include <rtems_config.h>
