/* 
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an 
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Partition Initialization
 * ============================================================================
 */

#include <bsp.h>

#include <air.h>
#include <pmk_plugin.h>

#include <imaspex.h>

int test_main(void);

/* Kernel Threads / Main Init launcher */
rtems_task Init (rtems_task_argument ignored) {
	rtems_status_code 	rc;

	
	/* imaspex start */
    imaspex_init();
	
	test_main();
	

	rc = rtems_task_delete( RTEMS_SELF );

	/* SKY 2010/04 : Dead Code to avoid code removal : TODO review this */
	rc = rtems_task_suspend		( RTEMS_SELF );
	rc = rtems_task_is_suspended( RTEMS_SELF );
	rc = rtems_task_resume		( RTEMS_SELF );
	
}
/* configuration information */

#define CONFIGURE_MAXIMUM_TASKS 			15
#define CONFIGURE_MAXIMUM_SEMAPHORES		15

#define CONFIGURE_INIT_TASK_ATTRIBUTES RTEMS_FLOATING_POINT

#include "../config/usr_rtems_config.h"

#include <rtems/confdefs.h>
