/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : RTEMS configuration
 * ============================================================================
 */

#include <rtems.h>

/**
 * @brief Standard RTEMS configuration
 */
#define CONFIGURE_INIT_TASK_ATTRIBUTES                  RTEMS_FLOATING_POINT

#define CONFIGURE_MICROSECONDS_PER_TICK 2000

#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_SIMPLE_CONSOLE_DRIVER

#define CONFIGURE_MAXIMUM_TASKS                         20
#define CONFIGURE_MAXIMUM_TIMERS 4

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

#define CONFIGURE_MAXIMUM_PROCESSORS 4

#define CONFIGURE_INIT

#define CONFIGURE_MAXIMUM_SEMAPHORES 1

#define CONFIGURE_SCHEDULER_PRIORITY_AFFINITY_SMP

#include <rtems/confdefs.h>
