/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an I/O
 * partition configuration. 
 * File Purpose:	IO Partition user configuration. Contains the configuration 
 * 					options for Ethernet's GRSPW devices.
 * ============================================================================
 */
#include <iop.h>
#include <IOPgrspw_router.h>
#include <spw_support.h>
#include <routing_table.h>

/** @brief  GRSPW control structure*/
static router_priv_t spwrtr_driver = \
{
	/* Router tables */
	.routes = rtr_routes,
	.ps = rtr_ps,
	.timer_reload = ps_timer
};

/** @brief GRSPW driver configuration */
static iop_spw_router_device_t device_configuration = \
{
    /* device configuration */
    .dev        = {

        .driver         = (void *)&spwrtr_driver,
        .init           = router_initialize,
        .open           = router_open,
        .read           = NULL,
        .write          = NULL,
        .close          = router_close,
    },

    /* spacewire router configuration configuration */
	.flags		= 11111,
	.config		= 10000,
	.iid		= 1,
	.idiv		= 1
};

/**
 * @brief Device Scheduling
 */
static uint32_t reads_per_period[] = \
    { 5 };

/**
 * @brief Routes Headers
 */
static iop_header_t route_header[1] = \
{
        {
        .eth_header = {
            .dst_ip      = { 192,168,0,2},
            .dst_mac     = { 0x68,0x05,0xca,0x1f,0x39,0xaf},
            .dst_port    = HTONS(14000),
            .src_port    = HTONS(14000)
        }
    }
};

/**
 * @brief Routes Scheduling
 */
static uint32_t route_schedule_0[1] = \
    { 1 };

/**
 * @brief Routes Configuration
 */
static iop_physical_route_t physical_routes[1] =\
{
    {
        .schedule   = route_schedule_0,
        .header     = &route_header[0],
        .port       = &remote_ports[1]
    }
};

/**
 * @brief Pysical Device configuration
 */
iop_physical_device_t physical_device_0 =\
{
    .driver             = (iop_device_driver_t *)&device_configuration,
    .routes             = {
        .length         = 1,
        .elements       = physical_routes
     },
    .reads_per_period   = reads_per_period,

    .reader_task        = NULL,
    .writer_task        = NULL,
    .header_prebuild    = NULL,
    .header_compare     = NULL,
    .header_copy        = NULL,
};
