/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an I/O
 * partition configuration. 
 * File Purpose:	IO Partition user configuration. Contains the configuration 
 * 					options for Ethernet's GRSPW devices.
 * ============================================================================
 */
#include <iop.h>
#include <IOPgrspw_router.h>
#include <spw_support.h>
#include <routing_table.h>

/** @brief  GRSPW control structure*/
static router_priv_t spwrtr_driver = \
{
	/* Router tables */
	.routes = &routes,
	.ps = &ps,
	.timer_reload = &timer_reload
};

/** @brief GRSPW driver configuration */
static iop_spw_router_device_t device_configuration = \
{
    /* device configuration */
    .dev        = {

        .driver         = (void *)&spwrtr_driver,
        .init           = router_initialize,
        .open           = router_open,
        .read           = NULL,
        .write          = NULL,
        .close          = router_close,
    },

    /* spacewire router configuration configuration */
	.flags		= 31,
	.config		= 14,
	.iid		= 1,
	.idiv		= 9
};

/**
 * @brief Device Scheduling
 */
static uint32_t reads_per_period[] = \
    { 5 };

/**
 * @brief Routes Headers
 */
static iop_header_t route_header[0] = \
{
};

/**
 * @brief Routes Scheduling
 */

/**
 * @brief Routes Configuration
 */
static iop_physical_route_t physical_routes[0] =\
{
};

/**
 * @brief Pysical Device configuration
 */
iop_physical_device_t physical_device_0 =\
{
    .driver             = (iop_device_driver_t *)&device_configuration,
    .routes             = {
        .length         = 0,
        .elements       = physical_routes
     },
    .reads_per_period   = reads_per_period,

    .reader_task        = spwrtr_reader,
    .writer_task        = spwrtr_writer,
    .header_prebuild    = NULL,
    .header_compare     = NULL,
    .header_copy        = NULL,
};
