/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Partition Initialization
 * ============================================================================
 */

// CODE WITH AIR DISABLED
//include <air.h>
#include <rtems.h>
#include "main.c"
#include "rtems_config.h"
/**
 * @brief Partition entry point
 */

/**
 * @brief Main RTEMS task
 */
rtems_task Init(rtems_task_argument ignored) {

    /* register HM ISR handler */
    /* HM is now Disabled
    rtems_isr_entry isr_ignored;
    rtems_interrupt_catch(
            (rtems_isr_entry)hm_isr_handler,
            AIR_IRQ_HM_EVENT,
            &isr_ignored);
    */

    /* call entry point */
    if (entry_point != NULL) {
        entry_point();
    }

    rtems_task_delete(RTEMS_SELF);
}

#include "rtems_config.h"


