/* 
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an 
 * AIR - ARINC 653 Interface in RTEMS - application configuration.
 * File Purpose  : Partition port definition
 * ============================================================================
 */

#include <rtems.h>
#include <string.h>

#include <pmk_plugin.h>
#include <pal_callbacks.h>
#include <air.h>

#define P0_NUMBER_OF_PORTS (0U)

