diff --git a/xky/Makefile.inc b/xky/Makefile.inc
index fa5e227..2708cb1 100755
--- a/xky/Makefile.inc
+++ b/xky/Makefile.inc
@@ -96,7 +96,7 @@ endef
 
 # rtems-impr definitions
 RTEMS_DIRECTORY=rtems-impr
-RTEMS_TARGET=sparc-rtems4.8
+RTEMS_TARGET=sparc-rtems
 RTEMS_BSP=leon3
 RTEMS_EXTERNAL_LIBRARY=edilib/library

diff --git a/xky/pos/rtems-impr/edilib/Makefile b/xky/pos/rtems-impr/edilib/Makefile
index 247e80f..439faae 100755
--- a/xky/pos/rtems-impr/edilib/Makefile
+++ b/xky/pos/rtems-impr/edilib/Makefile
@@ -1,7 +1,7 @@
 # definition of the compiler, archiver and ranlib (in the future, this should be obtained by searching in the cross-compiler definitions)
-CC = sparc-rtems4.8-gcc
-AR = sparc-rtems4.8-ar
-RANLIB = sparc-rtems4.8-ranlib
+CC = sparc-rtems-gcc
+AR = sparc-rtems-ar
+RANLIB = sparc-rtems-ranlib
 
 # change this directory for your path to the RTEMS directory (change this line for your specific settings)
 RTEMS_SOURCE_PATH = /rtems/mcoutinho/rtems/rtems-impr
