#!/bin/bash

# Access the variable passed as command-line argument
AIR=$1
EXAMPLE_NAME=$2
UTILS=$3

# Logic to generate the YAML content
cat > test.yml <<EOF
.ARM-QEMU-validation-template:
    stage: validation_tests
    needs: ["ARM-QEMU-hello_world","ARM-QEMU-bare_c"]
    tags:  ["ARM"]
    script: 
        - cd \$AIR/examples/private-example/private/validation/\$EXAMPLE_NAME
        - *build-executable
        - (\$UTILS/rvs_arm_coverage-ci.bash | tee testresult.txt) || true
        - *check-and-publish
    rules:
        - if: \$CI_PIPELINE_SOURCE == "merge_request_event"
        - if: '\$CI_PIPELINE_SOURCE == "schedule"'


.SPARC-LAYSIM-validation-template:
  stage: validation_tests
  needs: ["SPARC-LAYSIM-hello-world"] # ,"SPARC-LAYSIM-bare_c","SPARC-LAYSIM-hm","SPARC-LAYSIM-ports","SPARC-LAYSIM-shm","SPARC-LAYSIM-paranoia","SPARC-LAYSIM-smp01","SPARC-LAYSIM-smp02"]
  tags:  ["SPARC","LAYSIM"]
  script: 
        - echo "The value of TEST_NUMBER is $TEST_NUMBER"
        - cd $AIR/examples/private-example/private/validation/$EXAMPLE
        - *build-executable
        - laysim-gr740-mmu-cli -batch ../../../../../rvs_air/scripts/laysim_cmds.txt | tee testresult.txt
        - make distclean -i # Ignore distclean errors
        - *check-and-publish
  rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        
EOF