#!/bin/bash

# Access the variable passed as command-line argument
TEST_NUMBER=$1
AIR=$2

# Logic to generate the YAML content
cat > test.yml <<EOF

.SPARC-LAYSIM-validation-template:
  stage: validation_tests
  needs: ["SPARC-LAYSIM-hello-world"] # ,"SPARC-LAYSIM-bare_c","SPARC-LAYSIM-hm","SPARC-LAYSIM-ports","SPARC-LAYSIM-shm","SPARC-LAYSIM-paranoia","SPARC-LAYSIM-smp01","SPARC-LAYSIM-smp02"]
  tags:  ["SPARC","LAYSIM"]
  script: 
        - echo "The value of TEST_NUMBER is $TEST_NUMBER"
        - cd $AIR/examples/private-example/private/validation/TEST-DEF-$TEST_NUMBER
        - *build-executable
        - laysim-gr740-mmu-cli -batch ../../../../../rvs_air/scripts/laysim_cmds.txt | tee testresult.txt
        - make distclean -i # Ignore distclean errors
        - *check-and-publish
        
SPARC-LAYSIM-TEST-DEF-$TEST_NUMBER:
    extends: .SPARC-LAYSIM-validation-template

EOF