/*
 * ============================================================================
 * This file was generated by the GMV's Configurator Tool and is part of an I/O
 * partition configuration. 
 * File Purpose:	IO Partition user configuration. Contains the routing 
 * 					configuration options of the IO Partition.
 * ============================================================================
 */

#include <iop.h>

/**
 * @brief Logical devices
 */
extern iop_logical_device_t logical_device_1;
extern iop_logical_device_t logical_device_2;


/**
 * @brief Sampling ports configurations
 */
static air_sampling_port_configuration_t sampling_ports[] = {
    {
        .max_message_size   = 8,
        .refresh_period     = 1000,
        .port_direction     = AIR_DESTINATION_PORT,
    },
    {
        .max_message_size   = 8,
        .refresh_period     = 1000,
        .port_direction     = AIR_DESTINATION_PORT,
    },
    {
        .max_message_size   = 8,
        .refresh_period     = 1000,
        .port_direction     = AIR_SOURCE_PORT,
    },
    {
        .max_message_size   = 8,
        .refresh_period     = 1000,
        .port_direction     = AIR_SOURCE_PORT,
    },
};

/**
 * @brief IOP remote ports
 */
iop_port_t remote_ports[4] = {
    {
        .type               = AIR_SAMPLING_PORT,
        .name               = "iop_receiver",
        .configuration      = &sampling_ports[0],
        .device             = &logical_device_1
    },
    {
        .type               = AIR_SAMPLING_PORT,
        .name               = "iop_receiver2",
        .configuration      = &sampling_ports[1],
        .device             = &logical_device_2
    },
    {
        .type               = AIR_SAMPLING_PORT,
        .name               = "iop_sender",
        .configuration      = &sampling_ports[2],
        .device             = NULL
    },
    {
        .type               = AIR_SAMPLING_PORT,
        .name               = "iop_sender2",
        .configuration      = &sampling_ports[3],
        .device             = NULL
    },
};

